*Project: Houses for sale*

**This notebook is designed to provide analysis of the West Midlands region current house prices.**

**These records have been scraped from Zoopla using the Google Chrome browser extension, Webscraper.**

___

In [224]:
import pandas as pd
import re

# Read the scraped housing data 
df = pd.read_csv('houses_for_sale_20250803.csv')

# Rename columns for meaning

df = df.rename(columns={
    'web-scraper-order':      'scrape_order',
    'web-scraper-start-url':  'start_url',
    'pagination-selector':    'pagination_selector',
    'data':                   'address',
    'data2':                  'price_prefix',
    'data3':                  'price',
    'data4':                  'listing_highlight',
    'data5':                  'listing_tag',
    'image-src':              'property_image_src',
    'data6':                  'contact_email',
    'data7':                  'contact_phone',
    'data8':                  'description',
    'rooms_and_sqft':         'rooms_and_sqft',
    'key_points':             'key_points',
    'agent_image-src':        'agent_logo'
})

# preview the first few rows
print(df.head())
df.describe(include='all')

   scrape_order                                          start_url  \
0  1754266007-1  https://www.zoopla.co.uk/for-sale/property/wes...
1  1754266007-2  https://www.zoopla.co.uk/for-sale/property/wes...
2  1754266007-3  https://www.zoopla.co.uk/for-sale/property/wes...
3  1754266007-4  https://www.zoopla.co.uk/for-sale/property/wes...
4  1754266007-5  https://www.zoopla.co.uk/for-sale/property/wes...

  pagination_selector                                            address  \
0                 NaN           Deen Crescent, Birmingham, Birmingham B8
1                 NaN            Webb Grove, Hockley Heath, Solihull B94
2                 NaN         The Edition, Brindley Drive, Birmingham B1
3                 NaN  Centenary Plaza, 18 Holliday Street, Birmigham B1
4                 NaN                                                NaN

          price_prefix     price     listing_highlight listing_tag  \
0                 From  £499,999  Property of the week    New home
1          Offers over  £425,000             Highlight         NaN
2                 From  £296,864             Highlight    New home
3  Offers in region of  £174,950                   NaN         NaN
4                  NaN       NaN                   NaN         NaN

   property_image_src contact_email contact_phone  \
0                 NaN         Email          Call
1                 NaN         Email          Call
2                 NaN         Email          Call
3                 NaN         Email          Call
4                 NaN           NaN           NaN

                                         description  \
0  Newly Developed Homes at Deen Crescent, Birmin...
1  This beautifully presented three bedroom semi-...
2  Introducing the first residence of its kind to...
3  * Tenanted until March 2020* A bright and airy...
4                                                NaN

                        rooms_and_sqft                 key_points  \
0            5 beds3 baths2 receptions  Chain freeFreeholdReduced
1  3 beds2 baths2 receptions912 sq. ft          Share of Freehold
2     1 bed1 bath1 reception830 sq. ft                   Freehold
3               1 bed1 bath1 reception                        NaN
4                                  NaN                        NaN

                                          agent_logo
0  https://st.zoocdn.com/zoopla_static_agent_logo...
1  https://st.zoocdn.com/zoopla_static_agent_logo...
2  https://st.zoocdn.com/zoopla_static_agent_logo...
3  https://st.zoocdn.com/zoopla_static_agent_logo...
4                                                NaN

,scrape_order,start_url,pagination_selector,address,price_prefix,price,listing_highlight,listing_tag,property_image_src,contact_email,contact_phone,description,rooms_and_sqft,key_points,agent_logo
count,8317,8317,7911,8030,4298,8030,6618,4336,0.0,8030,8001,8030,7918,6188,8029
unique,8317,7,273,6173,6,893,13,9,NaN,1,1,6957,910,225,691
top,1754266007-1,https://www.zoopla.co.uk/for-sale/property/wes...,https://www.zoopla.co.uk/for-sale/property/lei...,"Cartwright Court, 2 Victoria Road, Malvern WR14",Offers over,"£200,000",Chain free,Reduced,NaN,Email,Call,Say goodbye to costly renovations with this br...,1 bed1 bath1 reception,Freehold,https://st.zoocdn.com/zoopla_static_agent_logo...
freq,1,1189,29,27,1503,374,1657,1381,NaN,8030,8001,15,1703,1142,547
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The start_url has 7 unique values

In [225]:
# Check unique values in 'start_url' column
unique_start_urls = df['start_url'].unique()
print(f"The start_url has {len(unique_start_urls)} unique values")
# Display the unique start URLs
for url in unique_start_urls:
    print(url)

The start_url has 7 unique values
https://www.zoopla.co.uk/for-sale/property/west-midlands-county/?q=West%20Midlands%20%28County%29&search_source=for-sale
https://www.zoopla.co.uk/for-sale/property/warwickshire/?q=Warwickshire&radius=0&search_source=for-sale
https://www.zoopla.co.uk/for-sale/property/herefordshire/?q=Herefordshire&radius=10&search_source=for-sale
https://www.zoopla.co.uk/for-sale/property/staffordshire/?q=Staffordshire&radius=0&search_source=for-sale
https://www.zoopla.co.uk/for-sale/property/worcestershire/?q=Worcestershire&radius=0&search_source=for-sale
https://www.zoopla.co.uk/for-sale/property/shropshire/?q=Shropshire&radius=0&search_source=for-sale
https://www.zoopla.co.uk/for-sale/property/leicestershire/?q=Leicestershire&radius=0&search_source=for-sale

In [226]:
# Let's get these from the URL text ie. everyting after Let's get these from the URL text ie. everyting after "https://www.zoopla.co.uk/for-sale/property/" and before the next /
df['start_url'] = df['start_url'].str.extract(r'https://www\.zoopla\.co\.uk/for-sale/property/([^/]+)')
# preview the first few rows again
df['start_url'].unique()

# preview the first few rows again
#print(df['start_url'].unique())

array(['west-midlands-county', 'warwickshire', 'herefordshire',
       'staffordshire', 'worcestershire', 'shropshire', 'leicestershire'],
      dtype=object)

In [227]:
# title case the start_url values
df['start_url'] = df['start_url'].str.title()

In [228]:
# remove the hyphens and the word 'County'
df['start_url'] = df['start_url'].str.replace('-', ' ', regex=False)
df['start_url'] = df['start_url'].str.replace('County', '', regex=False)
# Display the unique start URLs
#print(df['start_url'].unique())

# Check unique values in 'start_url' column
unique_start_urls = df['start_url'].unique()
print(f"The start_url has {len(unique_start_urls)} unique values")
# Display the unique start URLs
for url in unique_start_urls:
    print(url)

The start_url has 7 unique values
West Midlands
Warwickshire
Herefordshire
Staffordshire
Worcestershire
Shropshire
Leicestershire

In [229]:
# rename the 'start_url' column to 'County'
df = df.rename(columns={'start_url': 'County'})

In [230]:
# Check unique values in 'County' column
unique_counties = df['County'].unique()
print(f"The County has {len(unique_counties)} unique values")
# Display the unique counties
for county in unique_counties:
    print(county)

The County has 7 unique values
West Midlands
Warwickshire
Herefordshire
Staffordshire
Worcestershire
Shropshire
Leicestershire

So now the columns are:

df = df.rename(columns={
    'web-scraper-order':      'scrape_order',
    'web-scraper-start-url':  'County', # previously start_url
    'pagination-selector':    'pagination_selector',
    'data':                   'address',
    'data2':                  'price_prefix',
    'data3':                  'price',
    'data4':                  'listing_highlight',
    'data5':                  'listing_tag',
    'image-src':              'property_image_src',
    'data6':                  'contact_email',
    'data7':                  'contact_phone',
    'data8':                  'description',
    'rooms_and_sqft':         'rooms_and_sqft',
    'key_points':             'key_points',
    'agent_image-src':        'agent_logo'
})

Let's drop the columns we don't need
'scrape_order',
'pagination_selector',
'contact_email',
'contact_phone',

First let's remind ourselves of their contents:

In [231]:
"""
Let's drop the columns we don't need
'scrape_order',
'pagination_selector',
'contact_email',
'contact_phone',

First let's remind ourselves of their contents:
"""
print(df[['scrape_order', 'pagination_selector', 'contact_email', 'contact_phone']].head())
# Now we can drop the columns
df = df.drop(columns=['scrape_order', 'pagination_selector', 'property_image_src', 'contact_email', 'contact_phone'])

   scrape_order pagination_selector contact_email contact_phone
0  1754266007-1                 NaN         Email          Call
1  1754266007-2                 NaN         Email          Call
2  1754266007-3                 NaN         Email          Call
3  1754266007-4                 NaN         Email          Call
4  1754266007-5                 NaN           NaN           NaN

In [232]:
df.head(20)

,County,address,price_prefix,price,listing_highlight,listing_tag,description,rooms_and_sqft,key_points,agent_logo
0,West Midlands,"Deen Crescent, Birmingham, Birmingham B8",From,"£499,999",Property of the week,New home,"Newly Developed Homes at Deen Crescent, Birmin...",5 beds3 baths2 receptions,Chain freeFreeholdReduced,https://st.zoocdn.com/zoopla_static_agent_logo...
1,West Midlands,"Webb Grove, Hockley Heath, Solihull B94",Offers over,"£425,000",Highlight,NaN,This beautifully presented three bedroom semi-...,3 beds2 baths2 receptions912 sq. ft,Share of Freehold,https://st.zoocdn.com/zoopla_static_agent_logo...
2,West Midlands,"The Edition, Brindley Drive, Birmingham B1",From,"£296,864",Highlight,New home,Introducing the first residence of its kind to...,1 bed1 bath1 reception830 sq. ft,Freehold,https://st.zoocdn.com/zoopla_static_agent_logo...
3,West Midlands,"Centenary Plaza, 18 Holliday Street, Birmigham B1",Offers in region of,"£174,950",NaN,NaN,* Tenanted until March 2020* A bright and airy...,1 bed1 bath1 reception,NaN,https://st.zoocdn.com/zoopla_static_agent_logo...
4,West Midlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,West Midlands,"Holliday Street, Birmingham B1",NaN,"£174,950",NaN,NaN,* Tenanted until September 2019* A bright and ...,1 bed1 bath1 reception,NaN,https://st.zoocdn.com/zoopla_static_agent_logo...
6,West Midlands,"The Orion Building, Navigation Street B5",NaN,"£185,000",NaN,NaN,Asset Residential are pleased to offer this st...,1 bed1 bath1 reception,NaN,https://st.zoocdn.com/zoopla_static_agent_logo...
7,West Midlands,"Orion Building, 90 Navigation Street, Birmingh...",Offers in region of,"£164,950",NaN,NaN,Avery Residential are proud to present the opp...,1 bed1 bath1 reception,NaN,https://st.zoocdn.com/zoopla_static_agent_logo...
8,West Midlands,"Waterfront Walk, Birmingham B1",NaN,"£189,995",Leasehold,NaN,We are pleased to present this one bedroom apa...,1 bed1 bath450 sq. ft,Leasehold,https://st.zoocdn.com/zoopla_static_agent_logo...
9,West Midlands,"90 Navigation Street, Birmingham City Centre B5",NaN,"£180,000",Chain free,Leasehold,A well presented and modern one bedroom apartm...,1 bed1 bath1 reception,Chain freeLeaseholdReduced,https://st.zoocdn.com/zoopla_static_agent_logo...
10,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,"£179,950",NaN,NaN,***reduced for A quick sale***Kingsland Estate...,1 bed1 bath1 reception,NaN,https://st.zoocdn.com/zoopla_static_agent_logo...
11,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,"£179,500",Leasehold,Reduced,***reduced for A quick sale***Kingsland Estate...,1 bed1 bath1 reception,LeaseholdReduced,https://st.zoocdn.com/zoopla_static_agent_logo...
12,West Midlands,"Wilton Court, Southbank Road, Kenilworth CV8",NaN,"£195,000",Premium,Chain free,Enjoy lunch on us when you take A tour of wilt...,1 bed1 bath1 reception,Open Day,https://st.zoocdn.com/zoopla_static_agent_logo...
13,West Midlands,"The Ketttleworks, 126 Pope Street 3Dw B1",Offers in region of,"£170,000",NaN,NaN,Avery Residential are proud to offer for sale ...,1 bed1 bath1 reception540 sq. ft,NaN,https://st.zoocdn.com/zoopla_static_agent_logo...
14,West Midlands,"The Bank I, 60 Sheepcote Street B16",Offers over,"£209,000",Leasehold,NaN,This stunning superior one bedroom apartment h...,1 bed1 bath1 reception462 sq. ft,Leasehold,https://st.zoocdn.com/zoopla_static_agent_logo...
15,West Midlands,"Arthur Place, Birmingham B1",NaN,"£160,000",Chain free,Reduced,Dixons are pleased to offer to the market this...,1 bed1 bath1 reception,Chain freeReduced,https://st.zoocdn.com/zoopla_static_agent_logo...
16,West Midlands,"Masshouse Plaza, Birmingham B5",NaN,"£160,000",Leasehold,Reduced,**EWS1 certifcate in place** Innovate Estate A...,1 bed1 bath1 reception,LeaseholdReduced,https://st.zoocdn.com/zoopla_static_agent_logo...
17,West Midlands,"Pope Street, Birmingham B1",Offers in region of,"£195,000",Leasehold,NaN,LV PROPERTY is proud to present this beautiful...,1 bed1 bath1 reception,Leasehold,https://st.zoocdn.com/zoopla_static_agent_logo...
18,West Midlands,"Jewel Court, 12 Legge Lane, Jewellery Quarter B1",Offers in region of,"£159,000",Leasehold,Reduced,A beautifully presented one bedroom apartment ...,1 bed1 bath1 reception,LeaseholdReduced,https://st.zoocdn.com/zoopla_static_agent_logo...
19,West Midlands,"The Heathlands, Rowley Regis B65",Offers over,"£170,000",Chain free,Freehold,"**chain free** An immaculate, modernised one b...",1 bed1 bath2 receptions,Chain freeFreehold,https://st.zoocdn.com/zoopla_static_agent_logo...

In [233]:
# There are over 600 agents!We will use agent logo number as the agent ID
# Get the number between the brackets in the URL
# print the full agent logo URLs
#print(df['agent_logo'].unique())
unique_agents = df['agent_logo'].unique()
# Check unique values in 'agent_logo' column
print(f"The agent_logo has {len(unique_agents)} unique values")
# Display the unique agent logos
for agent in unique_agents:
    print(agent)

# Extract the agent ID from the agent_logo URL replace the agent_logo column with the agent_id
# We have some NaN values, so we will fill them with '0' and convert to int

df['agent_id'] = df['agent_logo'].str.extract(r'(\d+)', expand=False).fillna('0').astype(int)
unique_agentIDs = df['agent_id'].unique()
# Check unique values in 'agent_id' column
print(f"The agent_id has {len(unique_agentIDs)} unique values")
# Display the unique agent IDs
for agent_id in unique_agentIDs:
    print(agent_id)

The agent_logo has 692 unique values
https://st.zoocdn.com/zoopla_static_agent_logo_(756594).png
https://st.zoocdn.com/zoopla_static_agent_logo_(753015).png
https://st.zoocdn.com/zoopla_static_agent_logo_(764439).png
https://st.zoocdn.com/zoopla_static_agent_logo_(72393).jpeg
nan
https://st.zoocdn.com/zoopla_static_agent_logo_(755202).png
https://st.zoocdn.com/zoopla_static_agent_logo_(653112).png
https://st.zoocdn.com/zoopla_static_agent_logo_(753960).png
https://st.zoocdn.com/zoopla_static_agent_logo_(708164).png
https://st.zoocdn.com/zoopla_static_agent_logo_(762284).png
https://st.zoocdn.com/zoopla_static_agent_logo_(640107).png
https://st.zoocdn.com/zoopla_static_agent_logo_(497149).png
https://st.zoocdn.com/zoopla_static_agent_logo_(728017).png
https://st.zoocdn.com/zoopla_static_agent_logo_(745100).png
https://st.zoocdn.com/zoopla_static_agent_logo_(762320).png
https://st.zoocdn.com/zoopla_static_agent_logo_(742870).png
https://st.zoocdn.com/zoopla_static_agent_logo_(246276).png
https://st.zoocdn.com/zoopla_static_agent_logo_(281709).png
https://st.zoocdn.com/zoopla_static_agent_logo_(732820).png
https://st.zoocdn.com/zoopla_static_agent_logo_(634609).png
https://st.zoocdn.com/zoopla_static_agent_logo_(124281).png
https://st.zoocdn.com/zoopla_static_agent_logo_(592296).png
https://st.zoocdn.com/zoopla_static_agent_logo_(124333).png
https://st.zoocdn.com/zoopla_static_agent_logo_(740407).png
https://st.zoocdn.com/zoopla_static_agent_logo_(561596).png
https://st.zoocdn.com/zoopla_static_agent_logo_(592259).png
https://st.zoocdn.com/zoopla_static_agent_logo_(746012).png
https://st.zoocdn.com/zoopla_static_agent_logo_(727891).png
https://st.zoocdn.com/zoopla_static_agent_logo_(757595).png
https://st.zoocdn.com/zoopla_static_agent_logo_(695437).png
https://st.zoocdn.com/zoopla_static_agent_logo_(715134).png
https://st.zoocdn.com/zoopla_static_agent_logo_(763572).png
https://st.zoocdn.com/zoopla_static_agent_logo_(730018).png
https://st.zoocdn.com/zoopla_static_agent_logo_(644074).png
https://st.zoocdn.com/zoopla_static_agent_logo_(473059).png
https://st.zoocdn.com/zoopla_static_agent_logo_(595292).png
https://st.zoocdn.com/zoopla_static_agent_logo_(708173).png
https://st.zoocdn.com/zoopla_static_agent_logo_(561829).png
https://st.zoocdn.com/zoopla_static_agent_logo_(309335).png
https://st.zoocdn.com/zoopla_static_agent_logo_(753012).png
https://st.zoocdn.com/zoopla_static_agent_logo_(615674).png
https://st.zoocdn.com/zoopla_static_agent_logo_(561508).png
https://st.zoocdn.com/zoopla_static_agent_logo_(335135).png
https://st.zoocdn.com/zoopla_static_agent_logo_(671488).png
https://st.zoocdn.com/zoopla_static_agent_logo_(37432).data
https://st.zoocdn.com/zoopla_static_agent_logo_(765015).png
https://st.zoocdn.com/zoopla_static_agent_logo_(265833).png
https://st.zoocdn.com/zoopla_static_agent_logo_(721330).png
https://st.zoocdn.com/zoopla_static_agent_logo_(274639).png
https://st.zoocdn.com/zoopla_static_agent_logo_(486565).png
https://st.zoocdn.com/zoopla_static_agent_logo_(714845).png
https://st.zoocdn.com/zoopla_static_agent_logo_(738976).png
https://st.zoocdn.com/zoopla_static_agent_logo_(714152).png
https://st.zoocdn.com/zoopla_static_agent_logo_(532903).png
https://st.zoocdn.com/zoopla_static_agent_logo_(640741).png
https://st.zoocdn.com/zoopla_static_agent_logo_(274612).png
https://st.zoocdn.com/zoopla_static_agent_logo_(410110).png
https://st.zoocdn.com/zoopla_static_agent_logo_(532900).png
https://st.zoocdn.com/zoopla_static_agent_logo_(640598).png
https://st.zoocdn.com/zoopla_static_agent_logo_(767691).png
https://st.zoocdn.com/zoopla_static_agent_logo_(404049).png
https://st.zoocdn.com/zoopla_static_agent_logo_(273913).png
https://st.zoocdn.com/zoopla_static_agent_logo_(62643).jpeg
https://st.zoocdn.com/zoopla_static_agent_logo_(764535).png
https://st.zoocdn.com/zoopla_static_agent_logo_(37429).data
https://st.zoocdn.com/zoopla_static_agent_logo_(133309).png
https://st.zoocdn.com/zoopla_static_agent_logo_(254831).png
https://st.zoocdn.com/zoopla_static_agent_logo_(709746).png
https://st.zoocdn.com/zoopla_static_agent_logo_(161759).png
https://st.zoocdn.com/zoopla_static_agent_logo_(763800).png
https://st.zoocdn.com/zoopla_static_agent_logo_(757458).png
https://st.zoocdn.com/zoopla_static_agent_logo_(760370).png
https://st.zoocdn.com/zoopla_static_agent_logo_(743449).png
https://st.zoocdn.com/zoopla_static_agent_logo_(733741).png
https://st.zoocdn.com/zoopla_static_agent_logo_(764304).png
https://st.zoocdn.com/zoopla_static_agent_logo_(766383).png
https://st.zoocdn.com/zoopla_static_agent_logo_(640056).png
https://st.zoocdn.com/zoopla_static_agent_logo_(766371).png
https://st.zoocdn.com/zoopla_static_agent_logo_(743551).png
https://st.zoocdn.com/zoopla_static_agent_logo_(754716).png
https://st.zoocdn.com/zoopla_static_agent_logo_(746018).png
https://st.zoocdn.com/zoopla_static_agent_logo_(716058).png
https://st.zoocdn.com/zoopla_static_agent_logo_(708182).png
https://st.zoocdn.com/zoopla_static_agent_logo_(761423).png
https://st.zoocdn.com/zoopla_static_agent_logo_(670713).png
https://st.zoocdn.com/zoopla_static_agent_logo_(762248).png
https://st.zoocdn.com/zoopla_static_agent_logo_(503635).png
https://st.zoocdn.com/zoopla_static_agent_logo_(761429).png
https://st.zoocdn.com/zoopla_static_agent_logo_(767289).png
https://st.zoocdn.com/zoopla_static_agent_logo_(750731).png
https://st.zoocdn.com/zoopla_static_agent_logo_(255067).png
https://st.zoocdn.com/zoopla_static_agent_logo_(761426).png
https://st.zoocdn.com/zoopla_static_agent_logo_(112897).png
https://st.zoocdn.com/zoopla_static_agent_logo_(732193).png
https://st.zoocdn.com/zoopla_static_agent_logo_(596116).png
https://st.zoocdn.com/zoopla_static_agent_logo_(743245).png
https://st.zoocdn.com/zoopla_static_agent_logo_(759866).png
https://st.zoocdn.com/zoopla_static_agent_logo_(670401).png
https://st.zoocdn.com/zoopla_static_agent_logo_(714167).png
https://st.zoocdn.com/zoopla_static_agent_logo_(711126).png
https://st.zoocdn.com/zoopla_static_agent_logo_(627939).png
https://st.zoocdn.com/zoopla_static_agent_logo_(753903).png
https://st.zoocdn.com/zoopla_static_agent_logo_(76090).jpeg
https://st.zoocdn.com/zoopla_static_agent_logo_(511089).png
https://st.zoocdn.com/zoopla_static_agent_logo_(686558).png
https://st.zoocdn.com/zoopla_static_agent_logo_(342307).png
https://st.zoocdn.com/zoopla_static_agent_logo_(700700).png
https://st.zoocdn.com/zoopla_static_agent_logo_(733336).png
https://st.zoocdn.com/zoopla_static_agent_logo_(45862).jpeg
https://st.zoocdn.com/zoopla_static_agent_logo_(248093).png
https://st.zoocdn.com/zoopla_static_agent_logo_(722785).png
https://st.zoocdn.com/zoopla_static_agent_logo_(410125).png
https://st.zoocdn.com/zoopla_static_agent_logo_(505166).png
https://st.zoocdn.com/zoopla_static_agent_logo_(54574).gif
https://st.zoocdn.com/zoopla_static_agent_logo_(718722).png
https://st.zoocdn.com/zoopla_static_agent_logo_(275795).png
https://st.zoocdn.com/zoopla_static_agent_logo_(650021).png
https://st.zoocdn.com/zoopla_static_agent_logo_(37411).data
https://st.zoocdn.com/zoopla_static_agent_logo_(417057).png
https://st.zoocdn.com/zoopla_static_agent_logo_(758999).png
https://st.zoocdn.com/zoopla_static_agent_logo_(457152).png
https://st.zoocdn.com/zoopla_static_agent_logo_(735406).png
https://st.zoocdn.com/zoopla_static_agent_logo_(751805).png
https://st.zoocdn.com/zoopla_static_agent_logo_(734782).png
https://st.zoocdn.com/zoopla_static_agent_logo_(755631).png
https://st.zoocdn.com/zoopla_static_agent_logo_(432957).png
https://st.zoocdn.com/zoopla_static_agent_logo_(258822).png
https://st.zoocdn.com/zoopla_static_agent_logo_(752799).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747539).png
https://st.zoocdn.com/zoopla_static_agent_logo_(591437).png
https://st.zoocdn.com/zoopla_static_agent_logo_(667188).png
https://st.zoocdn.com/zoopla_static_agent_logo_(754203).png
https://st.zoocdn.com/zoopla_static_agent_logo_(37414).data
https://st.zoocdn.com/zoopla_static_agent_logo_(757826).png
https://st.zoocdn.com/zoopla_static_agent_logo_(434240).png
https://st.zoocdn.com/zoopla_static_agent_logo_(130749).png
https://st.zoocdn.com/zoopla_static_agent_logo_(139097).png
https://st.zoocdn.com/zoopla_static_agent_logo_(665479).png
https://st.zoocdn.com/zoopla_static_agent_logo_(735646).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747839).png
https://st.zoocdn.com/zoopla_static_agent_logo_(37435).data
https://st.zoocdn.com/zoopla_static_agent_logo_(648969).png
https://st.zoocdn.com/zoopla_static_agent_logo_(533594).png
https://st.zoocdn.com/zoopla_static_agent_logo_(750950).png
https://st.zoocdn.com/zoopla_static_agent_logo_(761741).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747899).png
https://st.zoocdn.com/zoopla_static_agent_logo_(741565).png
https://st.zoocdn.com/zoopla_static_agent_logo_(709382).png
https://st.zoocdn.com/zoopla_static_agent_logo_(705068).png
https://st.zoocdn.com/zoopla_static_agent_logo_(721792).png
https://st.zoocdn.com/zoopla_static_agent_logo_(759953).png
https://st.zoocdn.com/zoopla_static_agent_logo_(243789).png
https://st.zoocdn.com/zoopla_static_agent_logo_(457785).png
https://st.zoocdn.com/zoopla_static_agent_logo_(744226).png
https://st.zoocdn.com/zoopla_static_agent_logo_(733162).png
https://st.zoocdn.com/zoopla_static_agent_logo_(51843).jpeg
https://st.zoocdn.com/zoopla_static_agent_logo_(410107).png
https://st.zoocdn.com/zoopla_static_agent_logo_(718719).png
https://st.zoocdn.com/zoopla_static_agent_logo_(759443).png
https://st.zoocdn.com/zoopla_static_agent_logo_(503713).png
https://st.zoocdn.com/zoopla_static_agent_logo_(735460).png
https://st.zoocdn.com/zoopla_static_agent_logo_(512116).png
https://st.zoocdn.com/zoopla_static_agent_logo_(679267).png
https://st.zoocdn.com/zoopla_static_agent_logo_(726646).png
https://st.zoocdn.com/zoopla_static_agent_logo_(497252).png
https://st.zoocdn.com/zoopla_static_agent_logo_(143386).png
https://st.zoocdn.com/zoopla_static_agent_logo_(410116).png
https://st.zoocdn.com/zoopla_static_agent_logo_(756561).png
https://st.zoocdn.com/zoopla_static_agent_logo_(767781).png
https://st.zoocdn.com/zoopla_static_agent_logo_(679167).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747599).png
https://st.zoocdn.com/zoopla_static_agent_logo_(744139).png
https://st.zoocdn.com/zoopla_static_agent_logo_(719244).png
https://st.zoocdn.com/zoopla_static_agent_logo_(732994).png
https://st.zoocdn.com/zoopla_static_agent_logo_(675591).png
https://st.zoocdn.com/zoopla_static_agent_logo_(295589).png
https://st.zoocdn.com/zoopla_static_agent_logo_(767697).png
https://st.zoocdn.com/zoopla_static_agent_logo_(458405).png
https://st.zoocdn.com/zoopla_static_agent_logo_(755985).png
https://st.zoocdn.com/zoopla_static_agent_logo_(472855).png
https://st.zoocdn.com/zoopla_static_agent_logo_(644426).png
https://st.zoocdn.com/zoopla_static_agent_logo_(717248).png
https://st.zoocdn.com/zoopla_static_agent_logo_(765309).png
https://st.zoocdn.com/zoopla_static_agent_logo_(410104).png
https://st.zoocdn.com/zoopla_static_agent_logo_(765984).png
https://st.zoocdn.com/zoopla_static_agent_logo_(724747).png
https://st.zoocdn.com/zoopla_static_agent_logo_(622512).png
https://st.zoocdn.com/zoopla_static_agent_logo_(766137).png
https://st.zoocdn.com/zoopla_static_agent_logo_(741283).png
https://st.zoocdn.com/zoopla_static_agent_logo_(719067).png
https://st.zoocdn.com/zoopla_static_agent_logo_(592287).png
https://st.zoocdn.com/zoopla_static_agent_logo_(561511).png
https://st.zoocdn.com/zoopla_static_agent_logo_(161641).png
https://st.zoocdn.com/zoopla_static_agent_logo_(753144).png
https://st.zoocdn.com/zoopla_static_agent_logo_(720594).png
https://st.zoocdn.com/zoopla_static_agent_logo_(274624).png
https://st.zoocdn.com/zoopla_static_agent_logo_(744148).png
https://st.zoocdn.com/zoopla_static_agent_logo_(756588).png
https://st.zoocdn.com/zoopla_static_agent_logo_(380012).png
https://st.zoocdn.com/zoopla_static_agent_logo_(206861).png
https://st.zoocdn.com/zoopla_static_agent_logo_(554657).png
https://st.zoocdn.com/zoopla_static_agent_logo_(759623).png
https://st.zoocdn.com/zoopla_static_agent_logo_(750011).png
https://st.zoocdn.com/zoopla_static_agent_logo_(704595).png
https://st.zoocdn.com/zoopla_static_agent_logo_(725794).png
https://st.zoocdn.com/zoopla_static_agent_logo_(757314).png
https://st.zoocdn.com/zoopla_static_agent_logo_(765168).png
https://st.zoocdn.com/zoopla_static_agent_logo_(760376).png
https://st.zoocdn.com/zoopla_static_agent_logo_(457176).png
https://st.zoocdn.com/zoopla_static_agent_logo_(242132).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747893).png
https://st.zoocdn.com/zoopla_static_agent_logo_(764952).png
https://st.zoocdn.com/zoopla_static_agent_logo_(666037).png
https://st.zoocdn.com/zoopla_static_agent_logo_(751772).png
https://st.zoocdn.com/zoopla_static_agent_logo_(755181).png
https://st.zoocdn.com/zoopla_static_agent_logo_(700734).png
https://st.zoocdn.com/zoopla_static_agent_logo_(715783).png
https://st.zoocdn.com/zoopla_static_agent_logo_(743800).png
https://st.zoocdn.com/zoopla_static_agent_logo_(670156).png
https://st.zoocdn.com/zoopla_static_agent_logo_(44209).data
https://st.zoocdn.com/zoopla_static_agent_logo_(644604).png
https://st.zoocdn.com/zoopla_static_agent_logo_(727597).png
https://st.zoocdn.com/zoopla_static_agent_logo_(752129).png
https://st.zoocdn.com/zoopla_static_agent_logo_(161644).png
https://st.zoocdn.com/zoopla_static_agent_logo_(742225).png
https://st.zoocdn.com/zoopla_static_agent_logo_(242569).png
https://st.zoocdn.com/zoopla_static_agent_logo_(755211).png
https://st.zoocdn.com/zoopla_static_agent_logo_(756198).png
https://st.zoocdn.com/zoopla_static_agent_logo_(720106).png
https://st.zoocdn.com/zoopla_static_agent_logo_(752225).png
https://st.zoocdn.com/zoopla_static_agent_logo_(760016).png
https://st.zoocdn.com/zoopla_static_agent_logo_(282393).png
https://st.zoocdn.com/zoopla_static_agent_logo_(752688).png
https://st.zoocdn.com/zoopla_static_agent_logo_(683247).png
https://st.zoocdn.com/zoopla_static_agent_logo_(634921).png
https://st.zoocdn.com/zoopla_static_agent_logo_(634918).png
https://st.zoocdn.com/zoopla_static_agent_logo_(640191).png
https://st.zoocdn.com/zoopla_static_agent_logo_(751736).png
https://st.zoocdn.com/zoopla_static_agent_logo_(723676).png
https://st.zoocdn.com/zoopla_static_agent_logo_(396305).png
https://st.zoocdn.com/zoopla_static_agent_logo_(720603).png
https://st.zoocdn.com/zoopla_static_agent_logo_(744412).png
https://st.zoocdn.com/zoopla_static_agent_logo_(707660).png
https://st.zoocdn.com/zoopla_static_agent_logo_(748496).png
https://st.zoocdn.com/zoopla_static_agent_logo_(719803).png
https://st.zoocdn.com/zoopla_static_agent_logo_(302045).png
https://st.zoocdn.com/zoopla_static_agent_logo_(752433).png
https://st.zoocdn.com/zoopla_static_agent_logo_(276229).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747845).png
https://st.zoocdn.com/zoopla_static_agent_logo_(341193).png
https://st.zoocdn.com/zoopla_static_agent_logo_(583826).png
https://st.zoocdn.com/zoopla_static_agent_logo_(683250).png
https://st.zoocdn.com/zoopla_static_agent_logo_(381970).png
https://st.zoocdn.com/zoopla_static_agent_logo_(511653).png
https://st.zoocdn.com/zoopla_static_agent_logo_(303933).png
https://st.zoocdn.com/zoopla_static_agent_logo_(275783).png
https://st.zoocdn.com/zoopla_static_agent_logo_(735682).png
https://st.zoocdn.com/zoopla_static_agent_logo_(751958).png
https://st.zoocdn.com/zoopla_static_agent_logo_(659174).png
https://st.zoocdn.com/zoopla_static_agent_logo_(744815).png
https://st.zoocdn.com/zoopla_static_agent_logo_(719653).png
https://st.zoocdn.com/zoopla_static_agent_logo_(260710).png
https://st.zoocdn.com/zoopla_static_agent_logo_(710777).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747863).png
https://st.zoocdn.com/zoopla_static_agent_logo_(747827).png
https://st.zoocdn.com/zoopla_static_agent_logo_(724945).png
https://st.zoocdn.com/zoopla_static_agent_logo_(451471).png
https://st.zoocdn.com/zoopla_static_agent_logo_(52202).jpeg
https://st.zoocdn.com/zoopla_static_agent_logo_(762011).png
https://st.zoocdn.com/zoopla_static_agent_logo_(272890).png
https://st.zoocdn.com/zoopla_static_agent_logo_(287000).png
https://st.zoocdn.com/zoopla_static_agent_logo_(37426).data
https://st.zoocdn.com/zoopla_static_agent_logo_(709379).png
https://st.zoocdn.com/zoopla_static_agent_logo_(112061).png
https://st.zoocdn.com/zoopla_static_agent_logo_(712551).png
https://st.zoocdn.com/zoopla_static_agent_logo_(749540).png
https://st.zoocdn.com/zoopla_static_agent_logo_(763638).png
https://st.zoocdn.com/zoopla_static_agent_logo_(704038).png
https://st.zoocdn.com/zoopla_static_agent_logo_(389225).png
https://st.zoocdn.com/zoopla_static_agent_logo_(335234).png
https://st.zoocdn.com/zoopla_static_agent_logo_(708185).png
https://st.zoocdn.com/zoopla_static_agent_logo_(711325).png
https://st.zoocdn.com/zoopla_static_agent_logo_(767532).png
https://st.zoocdn.com/zoopla_static_agent_logo_(752171).png
https://st.zoocdn.com/zoopla_static_agent_logo_(766074).png
https://st.zoocdn.com/zoopla_static_agent_logo_(692345).png
https://st.zoocdn.com/zoopla_static_agent_logo_(735727).png
https://st.zoocdn.com/zoopla_static_agent_logo_(734551).png
https://st.zoocdn.com/zoopla_static_agent_logo_(754602).png
https://st.zoocdn.com/zoopla_static_agent_logo_(762903).png
https://st.zoocdn.com/zoopla_static_agent_logo_(745739).png
https://st.zoocdn.com/zoopla_static_agent_logo_(746222).png
https://st.zoocdn.com/zoopla_static_agent_logo_(555808).png
https://st.zoocdn.com/zoopla_static_agent_logo_(712999).png
https://st.zoocdn.com/zoopla_static_agent_logo_(633507).png
https://st.zoocdn.com/zoopla_static_agent_logo_(254816).png
https://st.zoocdn.com/zoopla_static_agent_logo_(716497).png
https://st.zoocdn.com/zoopla_static_agent_logo_(700763).png
https://st.zoocdn.com/zoopla_static_agent_logo_(76277).png
https://st.zoocdn.com/zoopla_static_agent_logo_(690993).png
https://st.zoocdn.com/zoopla_static_agent_logo_(746051).png
https://st.zoocdn.com/zoopla_static_agent_logo_(759302).png
https://st.zoocdn.com/zoopla_static_agent_logo_(761531).png
https://st.zoocdn.com/zoopla_static_agent_logo_(722575).png
https://st.zoocdn.com/zoopla_static_agent_logo_(690996).png
https://st.zoocdn.com/zoopla_static_agent_logo_(116753).png
https://st.zoocdn.com/zoopla_static_agent_logo_(487497).png
https://st.zoocdn.com/zoopla_static_agent_logo_(718795).png
https://st.zoocdn.com/zoopla_static_agent_logo_(762095).png
https://st.zoocdn.com/zoopla_static_agent_logo_(114997).png
https://st.zoocdn.com/zoopla_static_agent_logo_(246920).png
https://st.zoocdn.com/zoopla_static_agent_logo_(55691).gif
https://st.zoocdn.com/zoopla_static_agent_logo_(466972).png
https://st.zoocdn.com/zoopla_static_agent_logo_(765177).png
https://st.zoocdn.com/zoopla_static_agent_logo_(130369).png
https://st.zoocdn.com/zoopla_static_agent_logo_(410122).png
https://st.zoocdn.com/zoopla_static_agent_logo_(71012).png
https://st.zoocdn.com/zoopla_static_agent_logo_(761072).png
https://st.zoocdn.com/zoopla_static_agent_logo_(733969).png
https://st.zoocdn.com/zoopla_static_agent_logo_(687571).png
https://st.zoocdn.com/zoopla_static_agent_logo_(670710).png
https://st.zoocdn.com/zoopla_static_agent_logo_(650263).png
https://st.zoocdn.com/zoopla_static_agent_logo_(686749).png
https://st.zoocdn.com/zoopla_static_agent_logo_(745604).png
https://st.zoocdn.com/zoopla_static_agent_logo_(654815).png
https://st.zoocdn.com/zoopla_static_agent_logo_(765597).png
https://st.zoocdn.com/zoopla_static_agent_logo_(746396).png
https://st.zoocdn.com/zoopla_static_agent_logo_(68164).bmp
https://st.zoocdn.com/zoopla_static_agent_logo_(730963).png
https://st.zoocdn.com/zoopla_static_agent_logo_(687104).png
https://st.zoocdn.com/zoopla_static_agent_logo_(134909).png
https://st.zoocdn.com/zoopla_static_agent_logo_(334624).png
https://st.zoocdn.com/zoopla_static_agent_logo_(729718).png

In [234]:
# We can now drop the agent_logo column
df = df.drop(columns=['agent_logo'])

In [235]:
df.columns

Index(['County', 'address', 'price_prefix', 'price', 'listing_highlight',
       'listing_tag', 'description', 'rooms_and_sqft', 'key_points',
       'agent_id'],
      dtype='object')

In [236]:
# Let's get the first part of the postcode. It is the last part of the address eg. B1
# Notice that some postcodes are not in the format we expect, so we will need to remove them

df['postcode'] = df['address'].str.rstrip(',').str.split().str[-1].str.extract(r'\b([A-Z]{1,2}\d[A-Z\d]?)\b', expand=False)

# Check the new 'postcode' column

unique_postcodes = df['postcode'].unique()
print(f"The postcode has {len(unique_postcodes)} unique values")
# Display the unique postcodes
for postcodes in unique_postcodes:
    print(postcodes)
# number of rows with NaN postcodes
nan_postcodes = df['postcode'].isna().sum()
print(f"There are {nan_postcodes} rows with NaN postcodes")
# We can now drop the rows with NaN postcodes
df = df.dropna(subset=['postcode'])
unique_postcodes = df['postcode'].unique()
print(f"The postcode has {len(unique_postcodes)} unique values")

The postcode has 253 unique values
B8
B94
B1
nan
B5
CV8
B16
B65
B3
B15
B93
B74
B43
CV3
B44
B12
B18
B2
B72
B46
CV7
B37
B31
B91
B13
GL20
B26
B30
B73
DY8
WV6
CV1
B90
B92
DY9
B11
B67
B14
B9
WS2
B34
B24
DY6
B29
B28
B4
B68
DY4
CV6
B17
CV2
DY5
B21
WV14
B10
B69
B32
B23
B75
B27
B33
B20
WS1
B66
DY1
DY2
WV1
WV11
B36
WV3
WV2
B63
WS6
B45
WV4
WS9
CV4
CV5
WV13
WS8
B42
WS4
B6
B70
B48
WV12
WS5
WV10
B25
B19
B38
WS10
B76
B71
WV8
CV35
CV34
CV21
CV23
CV37
CV31
CV32
CV22
B49
CV33
B95
CV47
CV11
CV9
CV13
B80
B50
CV10
CV12
CV36
LE10
BR1
B98
GL19
DY13
HR9
WR14
WR1
SY7
GL1
HR4
NP25
GL2
HR7
NP7
GL14
WR8
WR6
GL16
GL17
GL15
HR2
HR6
WR4
GL18
HR8
SY8
LD1
HR1
WR15
WR13
LD3
WR5
HR5
LD7
WR2
LD2
HR3
LD8
WR7
GL4
WR3
DY14
NP16
NP8
GL3
B79
ST17
ST16
WS13
ST13
ST15
DE13
WS14
B78
ST8
ST7
WS15
WS11
ST6
ST10
B77
ST5
ST4
ST21
ST1
ST14
WS12
ST20
CW3
DE14
ST18
DE15
ST11
ST2
ST3
ST12
WS7
ST19
ST9
DY11
WR11
B97
B61
WR9
DY12
B60
DY10
WR10
WR12
B96
TF6
SY10
SY4
SY2
TF8
TF10
SY1
SY11
TF3
TF7
SY13
TF9
TF1
WV16
TF11
SY5
TF4
TF2
TF12
SY6
SY3
TF5
WV15
SY12
SY15
TF13
SY9
LL13
LE18
LE12
LE8
LE16
LE2
LE13
LE1
LE4
LE3
LE7
LE67
LE11
LE5
LE17
LE19
LE9
LE14
LE65
HP15
There are 291 rows with NaN postcodes
The postcode has 252 unique values

In [237]:
df.describe(include='all')

,County,address,price_prefix,price,listing_highlight,listing_tag,description,rooms_and_sqft,key_points,agent_id,postcode
count,8026,8026,4294,8026,6614,4334,8026,7915,6184,8026.000000,8026
unique,7,6169,6,893,13,9,6953,910,225,NaN,252
top,West Midlands,"Cartwright Court, 2 Victoria Road, Malvern WR14",Offers over,"£200,000",Chain free,Reduced,Say goodbye to costly renovations with this br...,1 bed1 bath1 reception,Freehold,NaN,WR14
freq,1148,27,1500,373,1656,1380,15,1703,1140,NaN,262
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,583302.166210,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199737.885994,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,481129.500000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,648969.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,747293.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,768084.000000,NaN

In [238]:
# convert the 'price' column to numeric, errors='coerce' will convert non-numeric values to NaN
df['price'] = pd.to_numeric(df['price'].str.replace('£', '').str.replace(',', ''), errors='coerce')

# convert the agent_id column to int
df['agent_id'] = df['agent_id'].astype(int)
print(df.dtypes)

County               object
address              object
price_prefix         object
price                 int64
listing_highlight    object
listing_tag          object
description          object
rooms_and_sqft       object
key_points           object
agent_id              int64
postcode             object
dtype: object

In [239]:
# show the first 20 rows
df.head(50)

,County,address,price_prefix,price,listing_highlight,listing_tag,description,rooms_and_sqft,key_points,agent_id,postcode
0,West Midlands,"Deen Crescent, Birmingham, Birmingham B8",From,499999,Property of the week,New home,"Newly Developed Homes at Deen Crescent, Birmin...",5 beds3 baths2 receptions,Chain freeFreeholdReduced,756594,B8
1,West Midlands,"Webb Grove, Hockley Heath, Solihull B94",Offers over,425000,Highlight,NaN,This beautifully presented three bedroom semi-...,3 beds2 baths2 receptions912 sq. ft,Share of Freehold,753015,B94
2,West Midlands,"The Edition, Brindley Drive, Birmingham B1",From,296864,Highlight,New home,Introducing the first residence of its kind to...,1 bed1 bath1 reception830 sq. ft,Freehold,764439,B1
3,West Midlands,"Centenary Plaza, 18 Holliday Street, Birmigham B1",Offers in region of,174950,NaN,NaN,* Tenanted until March 2020* A bright and airy...,1 bed1 bath1 reception,NaN,72393,B1
5,West Midlands,"Holliday Street, Birmingham B1",NaN,174950,NaN,NaN,* Tenanted until September 2019* A bright and ...,1 bed1 bath1 reception,NaN,72393,B1
6,West Midlands,"The Orion Building, Navigation Street B5",NaN,185000,NaN,NaN,Asset Residential are pleased to offer this st...,1 bed1 bath1 reception,NaN,72393,B5
7,West Midlands,"Orion Building, 90 Navigation Street, Birmingh...",Offers in region of,164950,NaN,NaN,Avery Residential are proud to present the opp...,1 bed1 bath1 reception,NaN,755202,B5
8,West Midlands,"Waterfront Walk, Birmingham B1",NaN,189995,Leasehold,NaN,We are pleased to present this one bedroom apa...,1 bed1 bath450 sq. ft,Leasehold,653112,B1
9,West Midlands,"90 Navigation Street, Birmingham City Centre B5",NaN,180000,Chain free,Leasehold,A well presented and modern one bedroom apartm...,1 bed1 bath1 reception,Chain freeLeaseholdReduced,753960,B5
10,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,179950,NaN,NaN,***reduced for A quick sale***Kingsland Estate...,1 bed1 bath1 reception,NaN,708164,B1
11,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,179500,Leasehold,Reduced,***reduced for A quick sale***Kingsland Estate...,1 bed1 bath1 reception,LeaseholdReduced,708164,B1
12,West Midlands,"Wilton Court, Southbank Road, Kenilworth CV8",NaN,195000,Premium,Chain free,Enjoy lunch on us when you take A tour of wilt...,1 bed1 bath1 reception,Open Day,762284,CV8
13,West Midlands,"The Ketttleworks, 126 Pope Street 3Dw B1",Offers in region of,170000,NaN,NaN,Avery Residential are proud to offer for sale ...,1 bed1 bath1 reception540 sq. ft,NaN,755202,B1
14,West Midlands,"The Bank I, 60 Sheepcote Street B16",Offers over,209000,Leasehold,NaN,This stunning superior one bedroom apartment h...,1 bed1 bath1 reception462 sq. ft,Leasehold,764439,B16
15,West Midlands,"Arthur Place, Birmingham B1",NaN,160000,Chain free,Reduced,Dixons are pleased to offer to the market this...,1 bed1 bath1 reception,Chain freeReduced,640107,B1
16,West Midlands,"Masshouse Plaza, Birmingham B5",NaN,160000,Leasehold,Reduced,**EWS1 certifcate in place** Innovate Estate A...,1 bed1 bath1 reception,LeaseholdReduced,497149,B5
17,West Midlands,"Pope Street, Birmingham B1",Offers in region of,195000,Leasehold,NaN,LV PROPERTY is proud to present this beautiful...,1 bed1 bath1 reception,Leasehold,728017,B1
18,West Midlands,"Jewel Court, 12 Legge Lane, Jewellery Quarter B1",Offers in region of,159000,Leasehold,Reduced,A beautifully presented one bedroom apartment ...,1 bed1 bath1 reception,LeaseholdReduced,745100,B1
19,West Midlands,"The Heathlands, Rowley Regis B65",Offers over,170000,Chain free,Freehold,"**chain free** An immaculate, modernised one b...",1 bed1 bath2 receptions,Chain freeFreehold,762320,B65
20,West Midlands,"James Street, Birmingham B3",NaN,210450,Leasehold,NaN,*Investors Only* An excellent modern developme...,1 bed1 bath1 reception,Leasehold,742870,B3
21,West Midlands,"5c Kensington Court, Highfield Road, Edgbaston...",NaN,196000,Reduced,NaN,Just Move Estate Agents and Lettings are delig...,1 bed1 bath1 reception,Reduced,246276,B15
22,West Midlands,"St. Pauls Square, Birmingham B3",NaN,159000,Chain free,Leasehold,Maguire Jackson are pleased to market this wel...,1 bed1 bath1 reception,Chain freeLeaseholdReduced,281709,B3
23,West Midlands,"Hagley Road, Birmingham B16",Offers over,175000,Auction,Leasehold,Auction - An amazing top floor mansion style a...,1 bed1 bath1 reception,AuctionLeasehold,732820,B16
24,West Midlands,"Fleet Street, Birmingham, West Midlands B3",Offers in region of,170000,NaN,NaN,Avery Residential are proud to offer for sale ...,1 bed1 bath1 reception,NaN,755202,B3
25,West Midlands,"Lincoln Apartments, 3 Lexington Gardens B15",NaN,159950,Leasehold,NaN,This modern one bedroom apartment is situated ...,1 bed1 bath1 reception,Leasehold,634609,B15
26,West Midlands,"Ryland Street, Birmingham B16",Guide price,159995,Chain free,Leasehold,Maguire Jackson is pleased to offer this one-b...,1 bed1 bath,Chain freeLeasehold,281709,B16
27,West Midlands,"Four Ashes Road, Solihull B93",Offers in region of,199000,Retirement,Leasehold,A beautifully presented one bed retirement liv...,1 bed1 bath,Self contained annexeCharacter,124281,B93
28,West Midlands,"The Mailbox, Royal Arch Apartments, Wharfside ...",NaN,179950,Chain free,Leasehold,"Reduced by £20,000. City living ... A well mai...",1 bed1 bath1 reception594 sq. ft,Chain freeLeaseholdReduced,592296,B1
29,West Midlands,"Deen Crescent, Birmingham, Birmingham B8",From,499999,Property of the week,New home,"Newly Developed Homes at Deen Crescent, Birmin...",5 beds3 baths2 receptions,Chain freeFreeholdReduced,756594,B8
30,West Midlands,"Webb Grove, Hockley Heath, Solihull B94",Offers over,425000,Highlight,NaN,This beautifully presented three bedroom semi-...,3 beds2 baths2 receptions912 sq. ft,Share of Freehold,753015,B94
31,West Midlands,"The Edition, Brindley Drive, Birmingham B1",From,296864,Highlight,New home,Introducing the first residence of its kind to...,1 bed1 bath1 reception830 sq. ft,Freehold,764439,B1
32,West Midlands,"Centenary Plaza, 18 Holliday Street, Birmigham B1",Offers in region of,174950,NaN,NaN,* Tenanted until March 2020* A bright and airy...,1 bed1 bath1 reception,NaN,72393,B1
34,West Midlands,"Holliday Street, Birmingham B1",NaN,174950,NaN,NaN,* Tenanted until September 2019* A bright and ...,1 bed1 bath1 reception,NaN,72393,B1
35,West Midlands,"The Orion Building, Navigation Street B5",NaN,185000,NaN,NaN,Asset Residential are pleased to offer this st...,1 bed1 bath1 reception,NaN,72393,B5
36,West Midlands,"Orion Building, 90 Navigation Street, Birmingh...",Offers in region of,164950,NaN,NaN,Avery Residential are proud to present the opp...,1 bed1 bath1 reception,NaN,755202,B5
37,West Midlands,"Waterfront Walk, Birmingham B1",NaN,189995,Leasehold,NaN,We are pleased to present this one bedroom apa...,1 bed1 bath450 sq. ft,Leasehold,653112,B1
38,West Midlands,"90 Navigation Street, Birmingham City Centre B5",NaN,180000,Chain free,Leasehold,A well presented and modern one bedroom apartm...,1 bed1 bath1 reception,Chain freeLeaseholdReduced,753960,B5
39,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,179950,NaN,NaN,***reduced for A quick sale***Kingsland Estate...,1 bed1 bath1 reception,NaN,708164,B1
40,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,179500,Leasehold,Reduced,***reduced for A quick sale***Kingsland Estate...,1 bed1 bath1 reception,LeaseholdReduced,708164,B1
41,West Midlands,"Wilton Court, Southbank Road, Kenilworth CV8",NaN,195000,Premium,Chain free,Enjoy lunch on us when you take A tour of wilt...,1 bed1 bath1 reception,Open Day,762284,CV8
42,West Midlands,"The Ketttleworks, 126 Pope Street 3Dw B1",Offers in region of,170000,NaN,NaN,Avery Residential are proud to offer for sale ...,1 bed1 bath1 reception540 sq. ft,NaN,755202,B1
43,West Midlands,"The Bank I, 60 Sheepcote Street B16",Offers over,209000,Leasehold,NaN,This stunning superior one bedroom apartment h...,1 bed1 bath1 reception462 sq. ft,Leasehold,764439,B16
44,West Midlands,"Arthur Place, Birmingham B1",NaN,160000,Chain free,Reduced,Dixons are pleased to offer to the market this...,1 bed1 bath1 reception,Chain freeReduced,640107,B1
45,West Midlands,"Masshouse Plaza, Birmingham B5",NaN,160000,Leasehold,Reduced,**EWS1 certifcate in place** Innovate Estate A...,1 bed1 bath1 reception,LeaseholdReduced,497149,B5
46,West Midlands,"Pope Street, Birmingham B1",Offers in region of,195000,Leasehold,NaN,LV PROPERTY is proud to present this beautiful...,1 bed1 bath1 reception,Leasehold,728017,B1
47,West Midlands,"Jewel Court, 12 Legge Lane, Jewellery Quarter B1",Offers in region of,159000,Leasehold,Reduced,A beautifully presented one bedroom apartment ...,1 bed1 bath1 reception,LeaseholdReduced,745100,B1
48,West Midlands,"The Heathlands, Rowley Regis B65",Offers over,170000,Chain free,Freehold,"**chain free** An immaculate, modernised one b...",1 bed1 bath2 receptions,Chain freeFreehold,762320,B65
49,West Midlands,"James Street, Birmingham B3",NaN,210450,Leasehold,NaN,*Investors Only* An excellent modern developme...,1 bed1 bath1 reception,Leasehold,742870,B3
50,West Midlands,"5c Kensington Court, Highfield Road, Edgbaston...",NaN,196000,Reduced,NaN,Just Move Estate Agents and Lettings are delig...,1 bed1 bath1 reception,Reduced,246276,B15
51,West Midlands,"St. Pauls Square, Birmingham B3",NaN,159000,Chain free,Leasehold,Maguire Jackson are pleased to market this wel...,1 bed1 bath1 reception,Chain freeLeaseholdReduced,281709,B3

In [240]:
# Need to split the 'rooms_and_sqft' column into separate columns for beds, baths, receptions, and sqft.
# # Regex with optional receptions and optional sqft
pattern = (
    r'(?P<beds>\d+)\s*beds?'              # beds
    r'(?P<baths>\d+)\s*baths?'            # baths
    r'(?:'                                # optional group for receptions
    r'(?P<receptions>\d+)\s*receptions?'  
    r')?'                                 # end optional
    r'(?:\s*(?P<sqft>\d+)\s*sq)?'         # optional sqft
)

# Extract and convert to nullable integers
extracted = df['rooms_and_sqft'].str.extract(pattern)
for col in ['beds', 'baths', 'receptions', 'sqft']:
    df[col] = pd.to_numeric(extracted[col], errors='coerce').astype('Int64')

# Now we can drop the 'rooms_and_sqft' column
df = df.drop(columns=['rooms_and_sqft'])
# Show the first few rows to confirm the changes
df.head(20)

,County,address,price_prefix,price,listing_highlight,listing_tag,description,key_points,agent_id,postcode,beds,baths,receptions,sqft
0,West Midlands,"Deen Crescent, Birmingham, Birmingham B8",From,499999,Property of the week,New home,"Newly Developed Homes at Deen Crescent, Birmin...",Chain freeFreeholdReduced,756594,B8,5,3,2,<NA>
1,West Midlands,"Webb Grove, Hockley Heath, Solihull B94",Offers over,425000,Highlight,NaN,This beautifully presented three bedroom semi-...,Share of Freehold,753015,B94,3,2,2,912
2,West Midlands,"The Edition, Brindley Drive, Birmingham B1",From,296864,Highlight,New home,Introducing the first residence of its kind to...,Freehold,764439,B1,1,1,1,830
3,West Midlands,"Centenary Plaza, 18 Holliday Street, Birmigham B1",Offers in region of,174950,NaN,NaN,* Tenanted until March 2020* A bright and airy...,NaN,72393,B1,1,1,1,<NA>
5,West Midlands,"Holliday Street, Birmingham B1",NaN,174950,NaN,NaN,* Tenanted until September 2019* A bright and ...,NaN,72393,B1,1,1,1,<NA>
6,West Midlands,"The Orion Building, Navigation Street B5",NaN,185000,NaN,NaN,Asset Residential are pleased to offer this st...,NaN,72393,B5,1,1,1,<NA>
7,West Midlands,"Orion Building, 90 Navigation Street, Birmingh...",Offers in region of,164950,NaN,NaN,Avery Residential are proud to present the opp...,NaN,755202,B5,1,1,1,<NA>
8,West Midlands,"Waterfront Walk, Birmingham B1",NaN,189995,Leasehold,NaN,We are pleased to present this one bedroom apa...,Leasehold,653112,B1,1,1,<NA>,450
9,West Midlands,"90 Navigation Street, Birmingham City Centre B5",NaN,180000,Chain free,Leasehold,A well presented and modern one bedroom apartm...,Chain freeLeaseholdReduced,753960,B5,1,1,1,<NA>
10,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,179950,NaN,NaN,***reduced for A quick sale***Kingsland Estate...,NaN,708164,B1,1,1,1,<NA>
11,West Midlands,"Holloway Circus Queensway, Birmingham B1",Offers over,179500,Leasehold,Reduced,***reduced for A quick sale***Kingsland Estate...,LeaseholdReduced,708164,B1,1,1,1,<NA>
12,West Midlands,"Wilton Court, Southbank Road, Kenilworth CV8",NaN,195000,Premium,Chain free,Enjoy lunch on us when you take A tour of wilt...,Open Day,762284,CV8,1,1,1,<NA>
13,West Midlands,"The Ketttleworks, 126 Pope Street 3Dw B1",Offers in region of,170000,NaN,NaN,Avery Residential are proud to offer for sale ...,NaN,755202,B1,1,1,1,540
14,West Midlands,"The Bank I, 60 Sheepcote Street B16",Offers over,209000,Leasehold,NaN,This stunning superior one bedroom apartment h...,Leasehold,764439,B16,1,1,1,462
15,West Midlands,"Arthur Place, Birmingham B1",NaN,160000,Chain free,Reduced,Dixons are pleased to offer to the market this...,Chain freeReduced,640107,B1,1,1,1,<NA>
16,West Midlands,"Masshouse Plaza, Birmingham B5",NaN,160000,Leasehold,Reduced,**EWS1 certifcate in place** Innovate Estate A...,LeaseholdReduced,497149,B5,1,1,1,<NA>
17,West Midlands,"Pope Street, Birmingham B1",Offers in region of,195000,Leasehold,NaN,LV PROPERTY is proud to present this beautiful...,Leasehold,728017,B1,1,1,1,<NA>
18,West Midlands,"Jewel Court, 12 Legge Lane, Jewellery Quarter B1",Offers in region of,159000,Leasehold,Reduced,A beautifully presented one bedroom apartment ...,LeaseholdReduced,745100,B1,1,1,1,<NA>
19,West Midlands,"The Heathlands, Rowley Regis B65",Offers over,170000,Chain free,Freehold,"**chain free** An immaculate, modernised one b...",Chain freeFreehold,762320,B65,1,1,2,<NA>
20,West Midlands,"James Street, Birmingham B3",NaN,210450,Leasehold,NaN,*Investors Only* An excellent modern developme...,Leasehold,742870,B3,1,1,1,<NA>

In [241]:
# We now to convert the 'key_points' column to a list strings separated by commas using the fact that 
#df['key_points'] = df['key_points'].str.split(',').apply(lambda x:
df['key_points'].head(50)

# Add a separator before every internal capital letter
# leave existing spaces alone
# "Chain freeLeaseholdReduced" becomes "Chain free|Leasehold|Reduced"
import re

cleaned = (
    df['key_points']            
      .fillna('')               
      .str.replace(r'([a-z])([A-Z])', r'\1|\2', regex=True))
# write to a CSV file
cleaned.to_csv('key_points_cleaned.csv', index=False)

tokens = (
    cleaned.str.split('|')      # lists of bits
           .explode()           # one row per bit
           .str.strip()         # lose stray spaces
           .replace('', pd.NA)  # drop empties
           .dropna()
)

unique_feats = tokens.unique()
print(unique_feats)

['Chain free' 'Freehold' 'Reduced' 'Share of Freehold' 'Leasehold'
 'Open Day' 'Auction' 'Self contained annexe' 'Character' 'Retirement'
 'Good Transport Links' 'Parking' 'Lift' 'Concierge' 'Modern'
 'Available Now' 'Local Amenities' 'Open Plan'
 'Ideal for First Time Buyers' 'Investor Opportunity' 'No Chain'
 'Home of the Week' 'New Listing' 'Close to Train Station' 'Gym'
 'Cinema Room' 'Low mortgage5% deposit' 'Penthouse' 'Roof Terrace'
 'Attractive Views' 'Garden' 'City Centre' 'Balcony' 'Buy to Let'
 'Close to station' 'Lateral Living' 'Chain Free' 'Town Centre Location'
 'Village Setting' 'Pets allowed' 'Viewing Advised' 'Good Schools'
 'Garage' 'Conservatory' 'South Facing' 'Period Property' 'Detached'
 'Part Exchange' 'Help to Move' 'Large Garden' 'EV charging point'
 'Developer Incentives' 'EV car charging' 'Low mortgage'
 'Off Street Parking' '5% deposit' 'Out Building' 'Underfloor Heating'
 'Virtual Tour Available' 'Stamp Duty Paid' 'Rural Setting' 'Cul-de-Sac'
 'Listed Building' 'Bi-Fold Doors' 'Duplex' 'With Land' 'Corner Plot'
 'En Suite' 'Shared Ownership' 'Apartment' 'Garden Room'
 'Roof solar panels' 'Potential To Extend (STPP)Virtual Tour Available'
 'Deposit contribution' 'Communal garden' 'Flooring Included' 'Equestrian'
 'Integrated Appliances' 'Double Garage' 'Show Home Available' 'Extension'
 'Potential To Extend (STPP)' 'Gated Community' 'Residents Parking']

['Chain free' 'Freehold' 'Reduced' 'Share of Freehold' 'Leasehold'
 'Open Day' 'Auction' 'Self contained annexe' 'Character' 'Retirement'
 'Good Transport Links' 'Parking' 'Lift' 'Concierge' 'Modern'
 'Available Now' 'Local Amenities' 'Open Plan'
 'Ideal for First Time Buyers' 'Investor Opportunity' 'No Chain'
 'Home of the Week' 'New Listing' 'Close to Train Station' 'Gym'
 'Cinema Room' 'Low mortgage5% deposit' 'Penthouse' 'Roof Terrace'
 'Attractive Views' 'Garden' 'City Centre' 'Balcony' 'Buy to Let'
 'Close to station' 'Lateral Living' 'Chain Free' 'Town Centre Location'
 'Village Setting' 'Pets allowed' 'Viewing Advised' 'Good Schools'
 'Garage' 'Conservatory' 'South Facing' 'Period Property' 'Detached'
 'Part Exchange' 'Help to Move' 'Large Garden' 'EV charging point'
 'Developer Incentives' 'EV car charging' 'Low mortgage'
 'Off Street Parking' '5% deposit' 'Out Building' 'Underfloor Heating'
 'Virtual Tour Available' 'Stamp Duty Paid' 'Rural Setting' 'Cul-de-Sac'
 'Listed Building' 'Bi-Fold Doors' 'Duplex' 'With Land' 'Corner Plot'
 'En Suite' 'Shared Ownership' 'Apartment' 'Garden Room'
 'Roof solar panels' 'Potential To Extend (STPP)Virtual Tour Available'
 'Deposit contribution' 'Communal garden' 'Flooring Included' 'Equestrian'
 'Integrated Appliances' 'Double Garage' 'Show Home Available' 'Extension'
 'Potential To Extend (STPP)' 'Gated Community' 'Residents Parking']

In [244]:
# 1) read cleaned file
df_features = pd.read_csv("key_points_cleaned.csv")

# 2) split mixed-case strings → individual tokens
tokens = (
    df_features['key_points']
        .fillna('')
        .str.split('|')
        .explode()
        .str.strip()
)
tokens = tokens[tokens.ne('')]        # drop empties

# 3) count token frequencies
counts = tokens.value_counts()
print(counts.head(15))                # inspect the top 15

# pick the most common features
top_n   = 5
keepers = counts.head(top_n).index

# 4) add Boolean “is_…” columns for those features
for feat in keepers:
    col_name = 'is_' + re.sub(r'\s+', '_', feat.lower())
    df_features[col_name] = df_features['key_points']\
        .str.contains(feat, case=False, na=False)

# preview
print(df_features.head(20))

# it must be either Freehold or Leasehold check the is_freehold and is_leasehold columns
# 1️⃣ if both are False → make Freehold True
mask_both_false = (~df_features['is_freehold']) & (~df_features['is_leasehold'])
df_features.loc[mask_both_false, 'is_freehold'] = True

# 2️⃣ if both are True  → turn Freehold off (so exactly one flag stays True)
mask_both_true = df_features['is_freehold'] & df_features['is_leasehold']
df_features.loc[mask_both_true, 'is_freehold'] = False
df_features[['is_freehold', 'is_leasehold']].head(10)

key_points
Freehold                       3272
Reduced                        2582
Chain free                     2157
Leasehold                      1741
Retirement                      458
Auction                         193
Low mortgage5% deposit          114
Open Day                         98
Share of Freehold                51
Garden                           47
Low mortgage                     41
Viewing Advised                  37
No Chain                         33
Parking                          28
Ideal for First Time Buyers      26
Name: count, dtype: int64
                      key_points  is_freehold  is_reduced  is_chain_free  \
0    Chain free|Freehold|Reduced         True        True           True
1              Share of Freehold         True       False          False
2                       Freehold         True       False          False
3                            NaN        False       False          False
4                            NaN        False       False          False
5                            NaN        False       False          False
6                            NaN        False       False          False
7                      Leasehold        False       False          False
8   Chain free|Leasehold|Reduced        False        True           True
9                            NaN        False       False          False
10             Leasehold|Reduced        False        True          False
11                      Open Day        False       False          False
12                           NaN        False       False          False
13                     Leasehold        False       False          False
14            Chain free|Reduced        False        True           True
15             Leasehold|Reduced        False        True          False
16                     Leasehold        False       False          False
17             Leasehold|Reduced        False        True          False
18           Chain free|Freehold         True       False           True
19                     Leasehold        False       False          False

    is_leasehold  is_retirement
0          False          False
1          False          False
2          False          False
3          False          False
4          False          False
5          False          False
6          False          False
7           True          False
8           True          False
9          False          False
10          True          False
11         False          False
12         False          False
13          True          False
14         False          False
15          True          False
16          True          False
17          True          False
18         False          False
19          True          False

   is_freehold  is_leasehold
0         True         False
1         True         False
2         True         False
3         True         False
4         True         False
5         True         False
6         True         False
7        False          True
8        False          True
9         True         False